// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RandomFilms.Data;

#nullable disable

namespace RandomFilms.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220720192950_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "A43B9C3A-BCBC-4600-A726-15C9435477AF",
                            ConcurrencyStamp = "a0066114-5942-445b-baf0-477c172fea31",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "B3616F56-CD53-464D-8E6F-E49ADF2F3FB5",
                            ConcurrencyStamp = "1ebbff16-dcee-4901-8e96-895806be9681",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "E384D4E7-7B9A-4B31-9A94-CC566E344E5B",
                            ConcurrencyStamp = "72fa7ecd-8d8a-48a3-82fd-f303e6ccfae4",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "C553670B-3A92-4D8D-B841-D5850EE19B9B",
                            ConcurrencyStamp = "bc75fde5-d4a4-40e1-9eed-47f8f35ad773",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "DFAEB25F-EAA8-49F1-B18F-E3F13DAFD3C0",
                            RoleId = "C553670B-3A92-4D8D-B841-D5850EE19B9B"
                        },
                        new
                        {
                            UserId = "DFAEB25F-EAA8-49F1-B18F-E3F13DAFD3C0",
                            RoleId = "E384D4E7-7B9A-4B31-9A94-CC566E344E5B"
                        },
                        new
                        {
                            UserId = "DFAEB25F-EAA8-49F1-B18F-E3F13DAFD3C0",
                            RoleId = "B3616F56-CD53-464D-8E6F-E49ADF2F3FB5"
                        },
                        new
                        {
                            UserId = "DFAEB25F-EAA8-49F1-B18F-E3F13DAFD3C0",
                            RoleId = "A43B9C3A-BCBC-4600-A726-15C9435477AF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RandomFilms.Models.CountryFilmModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilmModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmModelId");

                    b.ToTable("FilmCountries");
                });

            modelBuilder.Entity("RandomFilms.Models.CountryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 50,
                            Name = "DR Congo"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 53,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 61,
                            Name = "France"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Holy See"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 78,
                            Name = "India"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 124,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 129,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Saint Kitts & Nevis"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 148,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Sao Tome & Principe	"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 160,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 161,
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 162,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 165,
                            Name = "St. Vincent & Grenadines"
                        },
                        new
                        {
                            Id = 166,
                            Name = "State of Palestine"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 185,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 186,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 187,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("RandomFilms.Models.FilmGenersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FilmModelId")
                        .HasColumnType("int");

                    b.Property<string>("Gener")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmModelId");

                    b.ToTable("FilmGeneres");
                });

            modelBuilder.Entity("RandomFilms.Models.FilmModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Age")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackGroundImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryFilmModelId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilmGenereModelId")
                        .HasColumnType("int");

                    b.Property<double>("IMDB")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<string>("TrailerURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("RandomFilms.Models.GenreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Genre")
                        .IsUnique()
                        .HasFilter("[Genre] IS NOT NULL");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Anime"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Adult"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Adventure"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Animation"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Biography"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Comedy"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Documentary"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Drama"
                        },
                        new
                        {
                            Id = 11,
                            Genre = "Family"
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Fantasy"
                        },
                        new
                        {
                            Id = 13,
                            Genre = "History"
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Horror"
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Musical"
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Music"
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Mystery"
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Romance"
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Sci-Fi"
                        },
                        new
                        {
                            Id = 20,
                            Genre = "Short"
                        },
                        new
                        {
                            Id = 21,
                            Genre = "Sport"
                        },
                        new
                        {
                            Id = 22,
                            Genre = "Thriller"
                        },
                        new
                        {
                            Id = 23,
                            Genre = "War"
                        },
                        new
                        {
                            Id = 24,
                            Genre = "Western"
                        });
                });

            modelBuilder.Entity("RandomFilms.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "DFAEB25F-EAA8-49F1-B18F-E3F13DAFD3C0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bb1f3675-748b-4d4b-b19b-57887b80c8a7",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEBHLtsG4mT8o5xqFqA7OAzogYcujWtJlL/XgL06LAoYDPaTSp3JJ5vdkcpRAXg2mmg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2ce96376-b3b0-4918-bf5d-c754857b268d",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RandomFilms.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RandomFilms.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RandomFilms.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RandomFilms.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RandomFilms.Models.CountryFilmModel", b =>
                {
                    b.HasOne("RandomFilms.Models.FilmModel", "Film")
                        .WithMany("Countries")
                        .HasForeignKey("FilmModelId")
                        .HasPrincipalKey("CountryFilmModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("RandomFilms.Models.FilmGenersModel", b =>
                {
                    b.HasOne("RandomFilms.Models.FilmModel", "Film")
                        .WithMany("Genre")
                        .HasForeignKey("FilmModelId")
                        .HasPrincipalKey("FilmGenereModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("RandomFilms.Models.FilmModel", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
